services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: school_management_app
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
